---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: intranet-nfs-pv
  labels:
    type: nfs-web-storage
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nconnect=8
  nfs:
    server: jigen
    path: /protected/fleetwood/intranet
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: intranet-nfs-pvc
  namespace: family
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Mi
  selector:
    matchLabels:
      type: nfs-web-storage
  storageClassName: ""
