---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-config
  namespace: cummings-online-local
data:
  config: |
    options {
      directory "/var/cache/bind";
      dnssec-validation auto;
    };
    zone "cummings-online.local" {
      type master;
      file "/etc/bind/db.cummings-online.local";
    };
  zone: |
    $TTL 86400
    @           IN    SOA   ns.cummings-online.local. admin.cummings-online.local. (
                    2   ; serial
                86400   ; refresh
                28800   ; retry
               604800   ; expire
                86400)  ; negative cache ttl
    @           IN    NS    ns.cummings-online.local.
    jigen       IN    A     192.168.68.21
    awx         IN    CNAME jigen.cummings-online.local.
    netbox      IN    CNAME jigen.cummings-online.local.
    ns          IN    CNAME jigen.cummings-online.local.
    prometheus  IN    CNAME jigen.cummings-online.local.
    argocd      IN    CNAME jigen.cummings-online.local.
---
apiVersion: v1
kind: Service

metadata:
  name: bind9-service
  namespace: cummings-online-local
  labels:
    app: bind9
spec:
  selector:
    app: bind9
  ports:
  - protocol: TCP
    port: 5353
    targetPort: 53
    name: bind9-tcp
  - protocol: UDP
    port: 5353
    targetPort: 53
    name: bind9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9-deployment
  namespace: cummings-online-local
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      volumes:
        - name: config
          configMap:
            name: bind-config
            items:
              - key: config
                path: named.conf
              - key: zone
                path: db.cummings-online.local
      containers:
      - name: bind9
        image: ubuntu/bind9:edge
        env:
          - name: TZ
            value: America/Toronto
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        volumeMounts:
          - name: config
            mountPath: /etc/bind



