# ╭──────────────╮
# │LDAP Defaults ├─────────────────────────────────────────────────────────
# ╰──────────────╯

BASE	    dc=cummings-online,dc=ca
URI	    ldap://ldap2.cummings-online.ca ldap://ldap1.cummings-online.ca
SASL_MECH   GSSAPI
TLS_REQCERT hard
