dictionaries = ["en_gb"]
words = [
    "acpi",
    "analyzer",
    "ansible",
    "ansiblels",
    "antosha",
    "apic",
    "asmfmt",
    "augroup",
    "autoindent",
    "autopairs",
    "autoread",
    "autosession",
    "autotag",
    "avrtl",
    "bashls",
    "bibtex",
    "bootloaders",
    "bufnr",
    "cdrom",
    "chown",
    "cmake",
    "cmakelint",
    "codelldb",
    "colemak",
    "colorcolumn",
    "commentstring",
    "completeopt",
    "cssls",
    "cursorline",
    "customize",
    "cwd",
    "dap",
    "decremental",
    "desai",
    "dockerls",
    "efi",
    "emptor",
    "evdev",
    "expandtab",
    "fileencoding",
    "fileformat",
    "folke",
    "fzf",
    "ghci",
    "ghcups",
    "gitcommit",
    "gitsigns",
    "glyphs",
    "gmc",
    "gomod",
    "gopls",
    "gosum",
    "hls",
    "hlsearch",
    "hoogle",
    "hrsh",
    "hyperv",
    "hypr",
    "ignorecase",
    "incsearch",
    "integrations",
    "isort",
    "jglasovic",
    "josean",
    "jsonlint",
    "jsonls",
    "jsregexp",
    "kdheepak",
    "keybinds",
    "keymap",
    "keymaps",
    "kvm",
    "linters",
    "lspconfig",
    "lspkind",
    "luadoc",
    "lualine",
    "luasnip",
    "madhu",
    "makefiles",
    "mapleader",
    "markdownlint",
    "maximizer",
    "maxwidth",
    "menuone",
    "mfussenegger",
    "mkdir",
    "monokai",
    "nearline",
    "neovim",
    "netrw",
    "nginx",
    "nixd",
    "nixfmt",
    "nixos",
    "nixpkgs",
    "nmcli",
    "noatime",
    "noremap",
    "noselect",
    "nvim",
    "oldfiles",
    "openssl",
    "parsers",
    "pci",
    "pydocstyle",
    "pyproject",
    "pyright",
    "rstcheck",
    "rtc",
    "scrolloff",
    "sdb",
    "sdc",
    "sed",
    "shiftwidth",
    "signcolumn",
    "smartcase",
    "softtabstop",
    "splitbelow",
    "splitright",
    "starship",
    "stylelua",
    "stylua",
    "systemdlint",
    "tabclose",
    "tabn",
    "tabnew",
    "tabp",
    "tabstop",
    "tarmak",
    "termguicolors",
    "terraformls",
    "timeoutlen",
    "tlsv",
    "tmux",
    "tpm",
    "uefi",
    "unnamedplus",
    "vcpu",
    "vda",
    "venv",
    "vimdoc",
    "virtio",
    "vscode",
    "waybar",
    "wayland",
    "writeback",
    "xdg",
    "yamllint",
    "yamlls",
]
ignore_paths = ["nixos/README.md"]
ignore_patterns = ['\b[A-Z]{2,}\b']
