---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: cummings-online-local
spec:
  selector:
    run: redis
  type: ClusterIP
  ports:
    - name: postgres
      protocol: TCP
      port: 6379
      targetPort: 6379
