---
- name: Set common configurations
  tags:
    - config
    - configuration
  block:
    - name: Arch Common Configuration
      when: ansible_facts["os_family"] == "Archlinux"
      block:
        - name: Copy CA Arch
          ansible.builtin.copy:
            src: files/etc/ca-certificates/trust-source/anchors/ca.cummings-online.pem
            dest: /etc/ca-certificates/trust-source/anchors/ca.cummings-online.pem
            mode: "0644"
            owner: root
            group: root
          notify: Install CA Arch
        - name: SSH configuration
          ansible.builtin.copy:
            src: files/etc/ssh/sshd_config
            dest: /etc/ssh/sshd_config
            mode: "0644"
            owner: root
            group: root
          notify: Restart SSH Service ArchLinux

    - name: Debian Common Configuration
      when: ansible_facts["os_family"] == "Debian"
      block:
        - name: Copy CA Debian
          ansible.builtin.copy:
            src: files/etc/ca-certificates/trust-source/anchors/ca.cummings-online.pem
            dest: /usr/local/share/ca-certificates
            mode: "0644"
            owner: root
            group: root
          notify: Install CA Debian
        - name: SSH configuration
          ansible.builtin.copy:
            src: files/etc/ssh/sshd_config
            dest: /etc/ssh/sshd_config
            mode: "0644"
            owner: root
            group: root
          notify: Restart SSH Service Debian

    - name: Common Configuration
      when: ansible_facts["os_family"] == "Debian" or ansible_facts["os_family"] == "Archlinux"
      block:
        - name: Firewall Configuration
          block:
            - name: Firewall on
              community.general.ufw:
                state: enabled

            - name: Firewall default deny all in
              community.general.ufw:
                policy: deny
                direction: incoming

            - name: Firewall default allow all out
              community.general.ufw:
                policy: allow
                direction: outgoing

            - name: Firewall allow ssh
              community.general.ufw:
                rule: limit
                port: 2222
                proto: tcp

        - name: /etc/hosts configuration
          ansible.builtin.template:
            src: templates/hosts.j2
            dest: /etc/hosts
            mode: "0644"
            owner: root
            group: root

        - name: DNS Resolver configuration
          ansible.builtin.template:
            src: templates/resolv.conf.j2
            dest: /etc/resolv.conf
            mode: "0644"
            owner: root
            group: root

        - name: Systemd-resolved configuration
          ansible.builtin.template:
            src: templates/resolved.conf.j2
            dest: /etc/systemd/resolved.conf
            mode: "0644"
            owner: root
            group: root
          notify: Restart Resolved Service
