---
- name: Install CLI applications
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - calc
    - gnupg
    - jq
    - lsd
    - lsof
    - neovim
    - pandoc
    - pass
    - pinentry
    - starship
    - texlive
    - tmux
    - tree
    - jq

- name: Install Arch package management tools and CLI
  when: ansible_os_family == "ArchLinux"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - paru
    - yay
    - pinentry

- name: Install Debian package management tools and CLI
  when: ansible_os_family == "Debian"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - pinentry-tty
