---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: krb5-nfs-pv
  labels:
    type: nfs-model-storage
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nconnect=8
  nfs:
    server: jigen
    path: /protected/fleetwood/krb5
