---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 389ds-nfs-consumer-config-pv
  labels:
    type: nfs-389ds-consumer-config-storage
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nconnect=8
  nfs:
    server: lupin
    path: /protected/fleetwood/389ds/config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 389ds-nfs-consumer-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      type: nfs-389ds-consumer-config-storage
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 389ds-nfs-consumer-data-pv
  labels:
    type: nfs-389ds-consumer-data-storage
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nconnect=8
  nfs:
    server: lupin
    path: /protected/fleetwood/389ds/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 389ds-nfs-consumer-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  selector:
    matchLabels:
      type: nfs-389ds-consumer-data-storage
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 389ds-nfs-consumer-logs-pv
  labels:
    type: nfs-389ds-consumer-logs-storage
spec:
  capacity:
    storage: 1048Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nconnect=8
  nfs:
    server: lupin
    path: /protected/fleetwood/389ds/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 389ds-nfs-consumer-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1024Mi
  selector:
    matchLabels:
      type: nfs-389ds-consumer-logs-storage
  storageClassName: ""
