---
apiVersion: v1
kind: ConfigMap
metadata:
  name: 389ds-consumer-config
data:
  certmap.conf: |
    certmap default		default

    certmap CummingsPeople	OU=Cummings Online Identity CA,O=Cummings Online,C=CA,CN=Cummings Online Identity CA
    CummingsPeople:DNComps
    CummingsPeople:FilterComps    cn
    CummingsPeople:VerifyCert     on

    certmap CummingsSystems	OU=Cummings Online Component CA,O=Cummings Online,C=CA,CN=Cummings Online Component CA
    CummingsSystems:DNComps
    CummingsSystems:FilterComps    cn
    CummingsSystems:VerifyCert     off
