---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: 389ds-local-consumer-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer


# ───── Data ─────────────────────────────────────────
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 389ds-local-consumer-data-pv
spec:
  capacity:
    storage: 3072Mi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: 389ds-local-consumer-storage
  local:
    path: /srv/k8s/389ds/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - lupin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 389ds-consumer-data-pvc
  namespace: it
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: 389ds-local-consumer-storage
  resources:
    requests:
      storage: 3072Mi
