---
krb5:
  kdc:
    - krb2.cummings-online.ca
    - krb1.cummings-online.ca
    - krb.cummings-online.ca
  admin: krb.cummings-online.ca
ldap:
  servers:
    - ldap2.cummings-online.ca
    - ldap1.cummings-online.ca
    - ldap.cummings-online.ca
