preload = ~/.config/hypr/bg.jpg
splash = false
wallpaper{
  monitor = eDP-1
  path = ~/.config/hypr/bg.jpg
}
wallpaper{
  monitor = DP-1
  path = ~/.config/hypr/bg.jpg
}
wallpaper{
  monitor = DP-2
  path = ~/.config/hypr/bg.jpg
}
wallpaper{
  monitor = DP-3
  path = ~/.config/hypr/bg.jpg
}
wallpaper{
  monitor = HDMI-A-1
  path = ~/.config/hypr/bg.jpg
}
wallpaper{
  monitor = HDMI-A-2
  path = ~/.config/hypr/bg.jpg
}
wallpaper{
  monitor = HDMI-A-3
  path = ~/.config/hypr/bg.jpg
}

