# File: .config/hypr/goemon.conf
#
# ┌─ Individual System Configuration for Headless Servers ──────────────────────────────────────┐
# │                                                                                             │
# │ Devices, Monitors, Logging, Debugging, Inputs                                               │
# │                                                                                             │
# └─────────────────────────────────────────────────────────────────────────────────────────────┘

