---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: cummings-online-local
spec:
  selector:
    run: postgres
  type: ClusterIP
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432

