---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: cummings-online-local
spec:
  selector:
    app.kubernetes.io/name: postgres
  type: NodePort
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
