---
all:
  children:
    desktops:
      hosts:
        goemon.cummings-online.ca:
          ansible_connection: local
        children:
          thinkbooks:
            hosts:
              murasaki.cummings-online.ca:
              ansible_connection: local
    development:
      hosts:
        goemon.cummings-online.ca:
          ansible_connection: local
        murasaki.cummings-online.ca:
          ansible_connection: local
    montreal:
      hosts:
        goemon.cummings-online.ca:
          ansible_connection: local
        murasaki.cummings-online.ca:
          ansible_connection: local
