---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-nfs-pv
  labels:
    type: nfs-image-storage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nconnect=8
  nfs:
    server: jigen
    path: /protected/fleetwood/docker_registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      type: nfs-image-storage
  storageClassName: ""
