---
- name: Set up doamin client filesystems
  tags:
    - config
    - configuration
    - filesystems
  block:
    - name: NFS Mount Points
      ansible.builtin.file:
        path: "/mnt/nfs/{{ item }}"
        state: directory
        mode: "0755"
        owner: root
        group: root
      loop: "{{ nfs_servers }}"
