---
- name: Install system configuration utilities
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - openldap
    - krb5
    - nfs-utils
    # for nfs4
    - gssproxy
    # for ldap mechanism
    - cyrus-sasl-gssapi
