---
- name: Install system configuration utilities
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - openldap
    - krb5
    - nfs-utils
    # service for nfs4
    - gssproxy
    # library for ldap mechanism
    - cyrus-sasl-gssapi
  tags:
    - packages
    - domain-client
