---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 389ds-nfs-pv
  labels:
    type: nfs-model-storage
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nconnect=8
  nfs:
    server: jigen
    path: /fleetwood/389ds
