---
apiVersion: v1
kind: Service
metadata:
  name: ldap
  namespace: it
spec:
  selector:
    app: ldap
  ports:
    - name: ldap
      protocol: TCP
      port: 689
      targetPort: 689
  type: LoadBalancer
  loadBalancerIP: 10.11.0.12
