---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 389ds-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  selector:
    matchLabels:
      type: nfs-model-storage
  storageClassName: ""
