---
all:
  hosts:
    goemon.cummings-online.ca:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
    murasaki.cummings-online.ca:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
