---
name: PR to Branch Main
run-name: ${{ github.actor }} sends a PR to main
on:
  pull_request:
    branches: [main]
jobs:
  sanity_checks:
    runs-on: ubuntu-latest
    steps:
      - run: >
          echo "Checking if branch $${{ github.base_ref }} accepts PRs from
          branch ${{ github.head_ref}}"
      - run: \[ "develop" = "${{ github.head_ref }}" \] 
